baseURL = 'http://doudou.tech/'
languageCode = 'en-us'
title = 'doudou.tech'
theme        = "hello-friend-ng"
paginate     = 10

[Author]
name = "DoudouTech SL"

[params.footer]
    trademark = true
    author = true
    topText = ['<a href="/privacy">Privacy</a>']


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Software Creation Studio"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "We're a boutique studio focused on building products users enjoy"

  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Technology with a human touch"
    keywords = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "doudou.tech"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About us"
        url = "/about-us"

      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
